/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@celeris/ca-components')['Button']
    AConfigProvider: typeof import('@celeris/ca-components')['ConfigProvider']
    ADrawer: typeof import('@celeris/ca-components')['Drawer']
    AForm: typeof import('@celeris/ca-components')['Form']
    AFormItem: typeof import('@celeris/ca-components')['FormItem']
    AInput: typeof import('@celeris/ca-components')['Input']
    AMenu: typeof import('@celeris/ca-components')['Menu']
    AMenuItem: typeof import('@celeris/ca-components')['MenuItem']
    AResult: typeof import('@celeris/ca-components')['Result']
    ASubMenu: typeof import('@celeris/ca-components')['SubMenu']
    ATooltip: typeof import('@celeris/ca-components')['Tooltip']
    CAAppLogo: typeof import('@celeris/components')['CAAppLogo']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
